Bug 1774336 - Make FileInfoManagerGuard's default constructor public for C++20. r=saschanaz
C++20 changes to direct initialization with initializer lists make FileInfoManagerGuard's default constructor inaccessible.

https://en.cppreference.com/w/cpp/language/direct_initialization

dom/indexedDB/ActorsParent.cpp:12131:21: error: calling a private constructor of class 'mozilla::dom::indexedDB::FileInfoManager<mozilla::dom::indexedDB::DatabaseFileManager>::FileInfoManagerGuard'
                    FileInfoManagerGuard{}, SafeRefPtrFromThis(), id,
                    ^
dom/indexedDB/FileInfoManager.h:92:5: note: implicitly declared private here
    FileInfoManagerGuard() = default;
    ^

Differential Revision: https://phabricator.services.mozilla.com/D149349

UltraBlame original commit: c3875c2b32465dceb548dc814065d81d7944c9a2