Bug 1766646 - Vendor libwebrtc from f2126a5184e
Already cherry-picked in 7b370b935e.

Upstream commit: https://webrtc.googlesource.com/src/+/f2126a5184e3c125be0f73f57c6a7cb1e4c74f96
    Revert "Delete implicit conversion from raw pointer to scoped_ref_ptr"

    This reverts commit 7b370b935ec0dac991da08f9da227df9ce245fd5.

    Reason for revert: Breaking WebRTC in Chrome rolls. Roll can be found here https://chromium-review.googlesource.com/c/chromium/src/+/3436384/. Example failed build https://ci.chromium.org/ui/p/chromium/builders/try/chromeos-amd64-generic-rel-compilator/65973/overview. Failures seem to be in ChromeOS with the nearby library:
     error: no viable conversion from 'rtc::RefCountedObject<CreateSessionDescriptionObserverImpl> *' to 'rtc::scoped_refptr<CreateSessionDescriptionObserverImpl>'

    Original change's description:
    > Delete implicit conversion from raw pointer to scoped_ref_ptr
    >
    > Followup to https://webrtc-review.googlesource.com/c/src/+/242363
    >
    > Bug: webrtc:13464
    > Change-Id: I44358e8cfedeea92aac4ef47c540aff9a4865cdc
    > Reviewed-on: https://webrtc-review.googlesource.com/c/src/+/247362
    > Reviewed-by: Mirko Bonadei <mbonadeiwebrtc.org>
    > Reviewed-by: Tomas Gunnarsson <tommiwebrtc.org>
    > Commit-Queue: Niels Moller <nissewebrtc.org>
    > Cr-Commit-Position: refs/heads/main{#35897}

    TBR=mbonadeiwebrtc.org,nissewebrtc.org,tommiwebrtc.org,webrtc-scopedluci-project-accounts.iam.gserviceaccount.com

    Change-Id: Ib0beb44421519c8393131c55564c62c9b4d91504
    No-Presubmit: true
    No-Tree-Checks: true
    No-Try: true
    Bug: webrtc:13464
    Reviewed-on: https://webrtc-review.googlesource.com/c/src/+/250621
    Reviewed-by: Mirko Bonadei <mbonadeiwebrtc.org>
    Owners-Override: Mirko Bonadei <mbonadeiwebrtc.org>
    Commit-Queue: Mirko Bonadei <mbonadeiwebrtc.org>
    Cr-Commit-Position: refs/heads/main{#35905}

UltraBlame original commit: 8bdfbc8a7e333382a6049aebc3e4a08367755de2