Bug 1732208 - Silence the unused-but-set-variable warning in js/src. r=jandem
vm/TraceLogging.cpp:1685:12: error: variable 'totalJSTime' set but not used [-Werror,-Wunused-but-set-variable]
  uint32_t totalJSTime = 0;
           ^
wasm/WasmBinary.h:175:15: error: variable 'assertByte' set but not used [-Werror,-Wunused-but-set-variable]
      uint8_t assertByte = assertBits & 0x7f;
              ^
jit/x86-shared/MacroAssembler-x86-shared.cpp:406:11: error: variable 'diffG' set but not used [-Werror,-Wunused-but-set-variable]
  int32_t diffG = set.gprs().size() * sizeof(intptr_t);
          ^
jit/x86-shared/MacroAssembler-x86-shared.cpp:404:12: error: variable 'numFpu' set but not used [-Werror,-Wunused-but-set-variable]
  unsigned numFpu = fpuSet.size();
           ^
jit/x86-shared/MacroAssembler-x86-shared.cpp:455:11: error: variable 'diffG' set but not used [-Werror,-Wunused-but-set-variable]
  int32_t diffG = set.gprs().size() * sizeof(intptr_t);
          ^
jit/x86-shared/MacroAssembler-x86-shared.cpp:453:12: error: variable 'numFpu' set but not used [-Werror,-Wunused-but-set-variable]
  unsigned numFpu = fpuSet.size();
           ^
jit/x86-shared/MacroAssembler-x86-shared.cpp:503:12: error: variable 'numFpu' set but not used [-Werror,-Wunused-but-set-variable]
  unsigned numFpu = fpuSet.size();
           ^

Differential Revision: https://phabricator.services.mozilla.com/D126456

UltraBlame original commit: 7e04dd613276a5b9bf1e667f9cf20aef2953ab57