Bug 1776509 [wpt PR 34588] - Revert "Remove before/after phase and scroll offsets.", a=testonly
Automatic update from web-platform-tests
Revert "Remove before/after phase and scroll offsets."

This reverts commit 079c3deabde9f92b24e4b8746ee883e8b729c275.

Reason for revert: Compilation failure:
https://ci.chromium.org/ui/p/chromium/builders/ci/mac-archive-rel/34378/overview

third_party/blink/renderer/core/animation/scroll_timeline.cc:12:10: fatal error: 'third_party/blink/renderer/bindings/core/v8/v8_union_csskeywordvalue_cssnumericvalue_scrolltimelineelementbasedoffset_string.h' file not found

Original change's description:
> Remove before/after phase and scroll offsets.
>
> This patch removes deprecated pieces of code from scroll-timelines based
> on resolutions and direction in the spec rewrite.
>
> https://drafts.csswg.org/scroll-animations-1/rewrite
>
> Scroll timelines no longer have settable offsets.  Instead, each
> timeline has a single inferred pair of offsets. For the base
> ScrollTimeline class, this is presently based on the scroll range. For
> ViewTimelines, the range will likely be based on enter-start to
> exit-end (deferred to a followup patch).
>
> Bug: 1338167
>
> Change-Id: I64dc0114befc3432fe8645171c3c0b10995414eb
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3702953
> Reviewed-by: Robert Flack <flackrchromium.org>
> Commit-Queue: Kevin Ellis <keverschromium.org>
> Cr-Commit-Position: refs/heads/main{#1017766}

Bug: 1338167
Change-Id: I34eb2d28d554442f97f4c72737dc548664c154a2
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3724128
Auto-Submit: David Baron <dbaronchromium.org>
Owners-Override: David Baron <dbaronchromium.org>
Bot-Commit: Rubber Stamper <rubber-stamperappspot.gserviceaccount.com>
Commit-Queue: Rubber Stamper <rubber-stamperappspot.gserviceaccount.com>
Cr-Commit-Position: refs/heads/main{#1017784}

--

wpt-commits: f5026536100ca095e7d12c01de800b8a38057b83
wpt-pr: 34588

UltraBlame original commit: 5b9443b4177b46be9bfbfb2a39a014c79c7fb81b