Bug 1770107 - Disambiguate char16_t* operator== overloads in MinGW build for C++23. r=xpcom-reviewers,nika
C++23 is stricer about matching operator== overloads than C++17 and char16ptr_t's implicit constructor causes some overload confusion. We can disambigutate the operator== overloads by adding typed local variables without needing type casts.

xpcom/io/nsLinebreakConverter.cpp:447:17: error: use of overloaded operator '!=' is ambiguous (with operand types 'nsTSubstring<char16_t>::iterator' (aka 'char16_t *') and 'typename raw_type<char16_t, int>::type' (aka 'char16ptr_t'))
 if (stringBuf != aIoString.get()) {
     ~~~~~~~~~ ^  ~~~~~~~~~~~~~~~
mozilla/Char16.h:95:8: note: candidate function (with reversed parameter order)
 bool operator==(const char16ptr_t& aOther) const {
      ^
xpcom/io/nsLinebreakConverter.cpp:447:17: note: built-in candidate operator!=(const char16_t *, const char16_t *)
 if (stringBuf != aIoString.get()) {
               ^
xpcom/io/nsLinebreakConverter.cpp:447:17: note: built-in candidate operator!=(const volatile char16_t *, const volatile char16_t *)
xpcom/io/nsLinebreakConverter.cpp:447:17: note: built-in candidate operator!=(const void *, const void *)
xpcom/io/nsLinebreakConverter.cpp:447:17: note: built-in candidate operator!=(const volatile void *, const volatile void *)

Differential Revision: https://phabricator.services.mozilla.com/D146772

UltraBlame original commit: 2a10fbb3a9bfdd147bb946bc5aff4a826709e2b5