Bug 1491159 - More complete handling of TZ environment variable when initializing ICU timezone.  r=anba
This improves on the changes in bug 1484829 by handling the absolute
filename form of TZ environment variables both with and without an
initial ':' character, and by improving comments about relative and
absolute paths.  (Note that relative paths without the ':' are just
Olson time zone names.)

Note that the only test that failed without the patch was:
  setTimeZone("/usr/share/zoneinfo/America/Chicago");
  assertEq(timeZoneName(), "Central Daylight Time");
and it reported
  Error: Assertion failed: got "GMT-06:00", expected "Central Daylight Time"
which seems to be a sign that ICU gets some information out of that time
zone identifier (i.e., it reported the correct standard-time GMT
offset), but not everything.

Differential Revision: https://phabricator.services.mozilla.com/D5827

UltraBlame original commit: 75664900fcd9403abc477828c9ae93193bf4ee8f