Bug 1589487 [wpt PR 19768] - Reland "[Trusted Types] Remove TrustedURL.", a=testonly
Automatic update from web-platform-tests
Reland "[Trusted Types] Remove TrustedURL."

This reverts commit a84f1c65c3511283481a5a737a4b51d0abae7a92.

Reason for revert: wrong revert

Original change's description:
> Revert "[Trusted Types] Remove TrustedURL."
>
> This reverts commit 005483fe14c968325e6c8735eb6077049ee997ef.
>
> Reason for revert: <INSERT REASONING HERE>
> ../../third_party/blink/renderer/core/page/scrolling/text_fragment_anchor_test.cc(8,10): fatal error: 'third_party/blink/renderer/bindings/core/v8/usv_string_or_trusted_url.h' file not found
> #include "third_party/blink/renderer/bindings/core/v8/usv_string_or_trusted_url.h"
>
> Original change's description:
> > [Trusted Types] Remove TrustedURL.
> >
> > The current Trusted Types spec no longer supports TrustedURL. This CL adapts
> > to the spec.
> >
> > Bug: 1002555
> > Change-Id: I35c6d8a257046558f155b9f38289457b14dcb1d2
> > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1834142
> > Commit-Queue: Daniel Vogelheim <vogelheimchromium.org>
> > Reviewed-by: Mike West <mkwstchromium.org>
> > Cr-Commit-Position: refs/heads/master{#706886}
>
> TBR=vogelheimchromium.org,mkwstchromium.org
>
> Change-Id: I9012ad7c3f9f01389ab1aa7a90d5beb7873eab2c
> No-Presubmit: true
> No-Tree-Checks: true
> No-Try: true
> Bug: 1002555
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1866974
> Reviewed-by: Lan Wei <lanweichromium.org>
> Commit-Queue: Lan Wei <lanweichromium.org>
> Cr-Commit-Position: refs/heads/master{#706979}

TBR=vogelheimchromium.org,lanweichromium.org,mkwstchromium.org

Change-Id: Idfd715701037a3b3dfabe2adbb8f74b2e98625a0
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 1002555
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1865686
Reviewed-by: John Budorick <jbudorickchromium.org>
Commit-Queue: John Budorick <jbudorickchromium.org>
Cr-Commit-Position: refs/heads/master{#706986}

--

wpt-commits: 31cc136a9a9bd54f159eebfd8db4e9428f77cb37
wpt-pr: 19768

UltraBlame original commit: d26b600995ce3ce4685ebd6f6bdc2892583c6b8d