Bug 1732208 - Silence the unused-but-set-variable warning in parser. r=hsivonen
parser/html/nsHtml5StreamParser.cpp:1046:10: error: variable 'totalRead' set but not used [-Werror,-Wunused-but-set-variable]
  size_t totalRead = 0;
         ^

Differential Revision: https://phabricator.services.mozilla.com/D126458

UltraBlame original commit: d7e13f9ba1d3c57e64237a8b0438e59c2d216ee6