Bug 1756260 - part10 : fix macOS build error. r=media-playback-reviewers,bryce
> /builds/worker/fetches/MacOSX10.12.sdk/usr/include/MacTypes.h:542:16: error: reference to 'Point' is ambiguous

The point type conflicts with the `gfx::Point`, so move the media data out of the unify build.

Differential Revision: https://phabricator.services.mozilla.com/D146021

UltraBlame original commit: d2339ec8194ea6243024ac5325e304fd726b9f42