Bug 1765474 - Fix unused-but-set-variable warning in js/src. r=jandem
js/src/frontend/BytecodeEmitter.cpp:4893:12: error: variable 'count' set but not used [-Werror,-Wunused-but-set-variable]
  uint32_t count = cookedOrRaw->count();
           ^
js/src/frontend/BytecodeEmitter.cpp:4910:10: error: variable 'idx' set but not used [-Werror,-Wunused-but-set-variable]
  size_t idx;
         ^
js/src/irregexp/RegExpNativeMacroAssembler.cpp:899:10: error: variable 'pushedNonVolatileRegisters' set but not used [-Werror,-Wunused-but-set-variable]
  size_t pushedNonVolatileRegisters = 0;
         ^

Differential Revision: https://phabricator.services.mozilla.com/D144141

UltraBlame original commit: b06cd7b9964f6451196af11c58e0e6b19728e29e