Bug 1812154 - Vendor libwebrtc from b440c45797
Upstream commit: https://webrtc.googlesource.com/src/+/b440c4579767af8f72fbd2987c474d80a1bad297
    Unblock auto roller.

    Error message:
    Traceback (most recent call last):
      File "/b/s/w/ir/cache/builder/src/tools_webrtc/autoroller/roll_deps.py", line 778, in <module>
        sys.exit(main())
      File "/b/s/w/ir/cache/builder/src/tools_webrtc/autoroller/roll_deps.py", line 748, in main
        raise RollError('WebRTC DEPS entries are missing from Chromium: %s.\n'
    __main__.RollError: WebRTC DEPS entries are missing from Chromium: ['src/third_party/fuchsia-sdk/sdk'].
    Remove them or add them to either WEBRTC_ONLY_DEPS or DONT_AUTOROLL_THESE.

    src/third_party/fuchsia-sdk/sdk has been removed from
    https://crrev.com/c/3914609.

    Bug: None
    Change-Id: Ic2b7b39ffd1a3e5fb9bb73ddb1318a5e36b0bc30
    Reviewed-on: https://webrtc-review.googlesource.com/c/src/+/276720
    Reviewed-by: Andrey Logvin <landreygoogle.com>
    Commit-Queue: Daniel.L (Byoungchan) Lee <daniel.lhpcnt.com>
    Cr-Commit-Position: refs/heads/main{#38199}

UltraBlame original commit: 4d4947bdd5f56746b729d2593e9908b804ca1e63