Bug 1767471 [wpt PR 33912] - Fix Attributerrror for Chromium browser, a=testonly
Automatic update from web-platform-tests
Fix Attributerrror for Chromium browser (#33912)

self.last_url_used is compared with None but is never initialized to
None in class Chromium. This means that if the comparison is performed
before self.last_url_used is set to a valid value, wpt will crash with
message

AttributeError: 'Chromium' object has no attribute 'last_url_used'

This problem can be reproduced with this command line:

./wpt run --binary /usr/bin/chromium chromium

An alternate way to fix this would be to add a constructor to Chromium
class that initializes self.last_url_used, but this constructor will
also have to declare and pass parameters to Chromium's base class(es),
that will look more complicated compared to this patch.
--

wpt-commits: 26fe0c90387265f9d946ca036c4b4c2aca50c063
wpt-pr: 33912

UltraBlame original commit: acf12838d4e560aa15e6987bfcc8b13455db42a6