Bug 1832219 - Define _USE_MATH_DEFINES and M_PI on both regular and mingw Windows builds. r=firefox-build-system-reviewers,cubeb-reviewers,glandium,padenot
Without _USE_MATH_DEFINES, Windows' math.h doesn't define M_PI. Since _USE_MATH_DEFINES is defined globally, redundant definitions of _USE_MATH_DEFINES in moz.build files can be removed.

obj-build/dist/include/mozilla/ServoStyleConstsInlines.h:396:32: error: use of undeclared identifier 'M_PI'
obj-build/dist/include/mozilla/StaticPrefList_apz.h:133:22: error: use of undeclared identifier 'M_PI'
obj-build/dist/include/mozilla/gfx/PathHelpers.h:139:33: error: use of undeclared identifier 'M_PI'

Differential Revision: https://phabricator.services.mozilla.com/D177590

UltraBlame original commit: 41c57554a22def442936f41c00f8d59c5cdae6bc