Bug 1534108 [wpt PR 15651] - RTCError: Make "message" optional and be the last argument., a=testonly
Automatic update from web-platform-tests
RTCError: Make "message" optional and be the last argument.

Based on https://github.com/w3c/webrtc-pc/pull/2112.

Bug: 937844
Change-Id: I7ad149f47fb394f15055cc8fd77e79b4e5e0f317
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1499613
Commit-Queue: Henrik Boström <hboschromium.org>
Reviewed-by: Marina Ciocea <marinacioceachromium.org>
Cr-Commit-Position: refs/heads/master{#638192}

--

wpt-commits: e8831d9d354972a39ccfe388dd99eb5e2a6249a8
wpt-pr: 15651

UltraBlame original commit: e1daceb1b3e4816ee653b152d047f85742e3817e