Bug 1811714 - Add a few missing <cstdint> includes r=gfx-reviewers,nical
GCC 13s libstdc++ reduced its dependency on some headers like <cstdint>,
so it's no longer transitively included through various headers.
Include it explicitly.

See also: https://gcc.gnu.org/gcc-13/porting_to.html#header-dep-changes

  11:16.32 .../components/telemetry/pingsender/pingsender.cpp:30:7:
                    error: unknown type name 'uint32_t'
  11:16.33 const uint32_t kConnectionTimeoutMs = 30 * 1000;
  11:16.33       ^
  11:16.33 ... /components/telemetry/pingsender/pingsender.cpp:76:9:
                    error: unknown type name 'uint32_t'
  11:16.33   const uint32_t kBufferSize = 4 * 1024 - 1;
  11:16.34         ^
  11:16.44 2 errors generated.
  (et al)

Differential Revision: https://phabricator.services.mozilla.com/D167491

UltraBlame original commit: 61f052c26dd10f1bf64d1b34bdb769eda421d0fb