Bug 1765474 - Fix unused-but-set-variable warnings in netwerk/. r=necko-reviewers,dragana
netwerk/protocol/http/Http2Compression.cpp:326:12: error: variable 'removedCount' set but not used [-Werror,-Wunused-but-set-variable]
  uint32_t removedCount = 0;
           ^
netwerk/streamconv/converters/nsDirIndexParser.cpp:376:11: error: variable 'numItems' set but not used [-Werror,-Wunused-but-set-variable]
  int32_t numItems = 0;
          ^

Differential Revision: https://phabricator.services.mozilla.com/D144144

UltraBlame original commit: ea60e571a76ab1c15cc5e8ae58115c991200f94c