Bug 1517238 - [docs] Fix AttributeError: 'module' object has no attribute 'DirEntry' when running |mach doc|, r=davehunt
This was happening because one of the modules sphinx generates apidocs for
started depending on scandir and our in-tree vendored copy of scandir doesn't
have the C module built. I'm still not sure why this is failing though (scandir
is supposed to fall-back to ctypes if the C module doesn't exist).

Either way, adding scandir to tools/docs/Pipfile works around the problem.

Differential Revision: https://phabricator.services.mozilla.com/D15571

UltraBlame original commit: f13ad4df31b23f50ad6b1644f4c10490a21552f7