Bug 1829923 [wpt PR 39693] - [wptrunner] Content shell driver uses stdlib `subprocess`, a=testonly
Automatic update from web-platform-tests
[wptrunner] Content shell driver uses stdlib `subprocess` (#39693)

Per [0], use `subprocess` instead of `mozprocess`. This cleans up

```
  File "C:\b\s\w\ir\.task_template_vpython_cache\vpython\store\python_venv-jmti3st0nsnsdqnkri9ptk6dpk\contents\lib\site-packages\mozprocess\processhandler.py", line 714, in _custom_wait
    raise OSError(
  OSError: IO Completion Port failed to signal process shutdown
```

errors currently seen in the log [1]. All tests still run expectedly
with this change [2, 3].

Drive-by `wheelScroll.html` expectation update for Safari so
that CI can pass.

[0]: https://searchfox.org/mozilla-central/diff/3c0bcb202c7573129ce8af7f8bcfffa2389a2bc9/testing/mozbase/mozprocess/mozprocess/processhandler.py#9-10
[1]: https://chromium-swarm.appspot.com/task?id=61d187705a9fc610
[2]: https://ci.chromium.org/ui/p/chromium/builders/try/linux-wpt-content-shell-fyi-rel/1570/overview
[3]: https://ci.chromium.org/ui/p/chromium/builders/try/win10-wpt-content-shell-fyi-rel/1259/overview
--

wpt-commits: 17830ddb6a1f7a0cda9db142bed00eb8ffc7e52f
wpt-pr: 39693

UltraBlame original commit: d4c5a60640114c9edde8499bc9809e3dee639c9f