Bug 1732208 - Silence the unused-but-set-variable warning in toolkit/crashreporter. r=gsvelto
toolkit/crashreporter/breakpad-client/windows/crash_generation/minidump_generator.cc(319,35): error: variable 'dump_exception_pointers' set but not used [-Werror,-Wunused-but-set-variable]
  MINIDUMP_EXCEPTION_INFORMATION* dump_exception_pointers = NULL;
                                  ^

Differential Revision: https://phabricator.services.mozilla.com/D126460

UltraBlame original commit: 30d2381f3062d70835643e6302b6e98d4a49230a