Bug 1733034 - Fix unused-const-variable warnings in dom/security. r=freddyb
dom/security/nsCSPContext.cpp:80:23: error: unused variable 'CSP_CACHE_URI_CUTOFF_SIZE' [-Werror,-Wunused-const-variable]
static const uint32_t CSP_CACHE_URI_CUTOFF_SIZE = 512;
                      ^
dom/security/test/gtest/TestFilenameEvalParser.cpp:25:23: error: unused variable 'kDataUriWebExtCStyle' [-Werror,-Wunused-const-variable]
static constexpr auto kDataUriWebExtCStyle =
                      ^
dom/security/test/gtest/TestFilenameEvalParser.cpp:29:23: error: unused variable 'kOtherExtensionFile' [-Werror,-Wunused-const-variable]
static constexpr auto kOtherExtensionFile = "otherextension_file"_ns;
                      ^
dom/security/test/gtest/TestFilenameEvalParser.cpp:37:23: error: unused variable 'kOtherWorker' [-Werror,-Wunused-const-variable]
static constexpr auto kOtherWorker = "other-on-worker"_ns;
                      ^
dom/security/test/gtest/TestFilenameEvalParser.cpp:38:23: error: unused variable 'kRegexFailure' [-Werror,-Wunused-const-variable]
static constexpr auto kRegexFailure = "regexfailure"_ns;
                      ^

Differential Revision: https://phabricator.services.mozilla.com/D126869

UltraBlame original commit: f7e7d86b87abb4a965ff2b72fd0c33ede59e1007