Bug 1765474 - Fix unused-but-set-variable warning in OggDemuxer.cpp. r=media-playback-reviewers,padenot
dom/media/ogg/OggDemuxer.cpp:1905:7: error: variable 'hops' set but not used [-Werror,-Wunused-but-set-variable]
  int hops = 0;
      ^

Differential Revision: https://phabricator.services.mozilla.com/D144147

UltraBlame original commit: c8a797895bf9395fe4de5ab89ef1b00388fccc53