Bug 1800294 - clang-plugin: expect constexpr constructor error when compiling as C++17 but not C++20. r=firefox-static-analysis-reviewers,andi
C++20 allows non-trivial constexpr constructors, so this BadUnfortunateError check passes unexpectedly when compiled as C++20:

> error: 'error' diagnostics expected but not seen: build/clang-plugin/tests/TestTrivialCtorDtor.cpp Line 81: class 'BadUnfortunateError' must have trivial constructors and destructors

This constexpr constructor check was added in bug 1226376.

Differential Revision: https://phabricator.services.mozilla.com/D161951

UltraBlame original commit: e41a026123699f325cc4931a405d41c69ac729c5