Bug 1732208 - Silence the unused-but-set-variable warning in js/xpconnect. r=mccr8
js/xpconnect/src/XPCJSRuntime.cpp:2438:10: error: variable 'gcThingTotal' set but not used [-Werror,-Wunused-but-set-variable]
  size_t gcThingTotal = 0;
         ^

Differential Revision: https://phabricator.services.mozilla.com/D126457

UltraBlame original commit: 3799a2ddc4da5612f649c653090424970d9b8980