Bug 1733034 - Fix unused-const-variable warning in dom/media. r=padenot
dom/media/autoplay/AutoplayPolicy.cpp:38:23: error: unused variable 'sPOLICY_TRANSIENT_ACTIVATION' [-Werror,-Wunused-const-variable]
static const uint32_t sPOLICY_TRANSIENT_ACTIVATION = 1;
                      ^

Differential Revision: https://phabricator.services.mozilla.com/D126868

UltraBlame original commit: 2aa15daba9d01b182f9f96bf26e22f3cd909beed